apiVersion: v1
kind: Template
metadata:
  name: python-web-server
labels:
  name: "${APP_NAME}"
  rndid: "${APP_NAME}"
parameters:
- name: APP_NAME
  description: App name
  value: python-web-server
- name: DOCKER_REGISTRY
  description: App name
  #value: docker-registry.default.svc:5000
  #docker-registry.default.svc 
  #docker-registry.default.svc.cluster.local

objects:  
- apiVersion: v1
  kind: Pod
  metadata:
    name: "${APP_NAME}"
  spec:
    containers:
      - name: "${APP_NAME}"
        image: "${DOCKER_REGISTRY}:5000/examples/${APP_NAME}:latest"
        command: ["/bin/sh"]
        args: ["-c", "python -m SimpleHTTPServer 8000"]    
        ports:
          - name: http
            containerPort: 8000

- kind: Service
  apiVersion: v1
  metadata:
    name: "${APP_NAME}"
  spec:
    ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
    selector:
      name: "${APP_NAME}"
    type: ClusterIP
    sessionAffinity: None
- apiVersion: v1
  kind: Route
  metadata:
    name: "${APP_NAME}"
  spec:
    to:
      kind: Service
      name: "${APP_NAME}"
    port:
      targetPort: http
