# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

  # always use Vagrants insecure key
  config.ssh.insert_key = false

  # set hostname
  #config.vm.hostname = ""
  
  # Do not upgrade vbox guest package
  config.vbguest.auto_update = false
  
  # Disable share
  config.vm.synced_folder ".", "/vagrant", disabled: true
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 2
    #vb.customize ["modifyvm", :id, "--cpuexecutioncap", 75]
    vb.gui = false
  end

  # Ansible provision
  # Inventory file is .vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "ansible/ping.yml"
  end
  
  # Create a forwarded port mapping which allows access to a specific port
  config.vm.network "forwarded_port", guest: 8080, host: 8080


  # Create a private network, which allows host-only access to the machine
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. 
  # config.vm.synced_folder "../data", "/vagrant_data"

  #
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL

  # File provision
  # config.vm.provision :file do |file|
  #   file.source = "./" #default to ansible folder
  #   file.destination = "${HOME}/ansible"
  # end
end
