apiVersion: v1
kind: Template
metadata:
  name: jupyter
labels:
  name: "${APP_NAME}"
  createdBy: jupyter
  rndid: jupyter
parameters:
- name: APP_NAME
  description: App name
  value: jupyter
- name: DOCKER_REGISTRY
  description: App name
  value: docker-registry.default.svc

objects:  
- apiVersion: v1
  kind: Pod
  metadata:
    name: "${APP_NAME}"
  spec:
    containers:
      - name: "${APP_NAME}"
        image: "${DOCKER_REGISTRY}:5000/jupyter/jupyter:latest"
        command: ["/bin/sh"]
        args: ["-c", "jupyter notebook --ip 0.0.0.0 --port 8000 --no-browser"]    
        ports:
          - name: http
            containerPort: 8000
        securityContext:
          privileged: true
        # resources:
        #   limits:
        #     nvidia.com/gpu: 1 # requesting 1 GPU

- kind: Service
  apiVersion: v1
  metadata:
    name: "${APP_NAME}"
  spec:
    ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
    selector:
      name: "${APP_NAME}"
    type: ClusterIP
    sessionAffinity: None
- apiVersion: v1
  kind: Route
  metadata:
    name: "${APP_NAME}"
  spec:
    to:
      kind: Service
      name: "${APP_NAME}"
    port:
      targetPort: http
