apiVersion: v1
kind: Template
metadata:
  name: jupyter
labels:
  createdBy: jupyter
  rndid: jupyter
parameters:
- name: APP_NAME
  description: App name
  value: jupyter
- name: SERVICE_ACCOUNT
  description: k8s service account
  value: gitlab
- name: APP_HOSTNAME
  description: Hostname for service routes
  value: gitlab-ci-python-web-server.127.0.0.1.nip.io

objects:  
- apiVersion: v1
  kind: Pod
  metadata:
    name: "${APP_NAME}"
  spec:
    containers:
      - name: "${APP_NAME}"
        image: openshift/jupyter:latest
#        serviceAccount: "${SERVICE_ACCOUNT}"
        command: ["/bin/sh"]
        args: ["-c", "jupyter notebook --ip 0.0.0.0 --port 8000"]    
        ports:
          - name: http
            containerPort: 8000
        # resources:
        #   limits:
        #     cpu: 750m
        #   requests:
        #     cpu: 750m

- kind: Service
  apiVersion: v1
  metadata:
    name: "${APP_NAME}"
  spec:
    ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
    selector:
      name: "${APP_NAME}"
    type: ClusterIP
    sessionAffinity: None
- apiVersion: v1
  kind: Route
  metadata:
    name: "${APP_NAME}"
  spec:
    host: "${APP_HOSTNAME}"
    to:
      kind: Service
      name: "${APP_NAME}"
    port:
      targetPort: http
