# -*- mode: ruby -*-
# # vi: set ft=ruby :

Vagrant.require_version ">= 1.9.0"

# Defaults for config options defined in CONFIG
$num_instances = 3
$vm_memory = 3072
$vm_cpus = 2
$vm_executioncap = 20 # Max host cpu used by any vm
$instance_name_prefix = "centos"
$share_folder = false
$vm_gui = false

Vagrant.configure("2") do |config|
  # always use Vagrants insecure key
  config.ssh.insert_key = false

  config.vm.box = "centos/7"

  # Type: virtualbox share data
  # Requirement: https://github.com/dotless-de/vagrant-vbguest
  # See https://github.com/mitchellh/vagrant/issues/7157
  if $share_folder == true
    config.vm.share_folder ".", "/vagrant", type: "virtualbox"
  else
    # disbale default shared folder
    config.vm.synced_folder ".", "/vagrant", disabled: true
  end

  # enable hostmanager
  config.hostmanager.enabled = true

  # configure the host's /etc/hosts
  config.hostmanager.manage_host = true

  (1..$num_instances).each do |i|
    config.vm.define vm_name = "%s-%02d" % [$instance_name_prefix, i] do |config|
      config.vm.hostname = vm_name

      config.vm.provider :virtualbox do |vb|
        vb.gui = $vm_gui
        vb.memory = $vm_memory
        vb.cpus = $vm_cpus
        vb.customize ["modifyvm", :id, "--cpuexecutioncap", $vm_executioncap]
      end

      ip = "192.168.50.#{i+100}"
      config.vm.network :private_network, ip: ip

    end
  end
  # Ansible Provisioning
  # Inventory file is .vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "ansible/ping.yml"
  end
end