# Drill dockerfile PR https://github.com/apache/drill/pull/1348/commits

FROM drill/apache-drill-centos:1.14.0-SNAPSHOT

ENTRYPOINT []

# Only for dev!
CMD  /opt/drill/bin/drill-embedded 

# TODO: change logback to printo to stdoutput, experiment with authentication
