# Example from an Ansible Playbook
---
- hosts:
  - all
  #gather_facts: False # Faster

  tasks:
  #- ping:
  - shell: whoami
    register: out

  - debug: msg="{{ out.stdout }}"

  - debug: msg="{{ out.stderr }}"

# Induce an exception to see what happens
# - ping:
#     data: crash