apiVersion: v1
kind: Pod
metadata:
  name: nfs-example
  labels:
    name: nfs-example
spec:
  containers:
    - name: nfs-example
      image: docker-registry.default.svc:5000/default/my-rhel
      command: ["/bin/sh"]
      args: ["-c", "while true; do msg=\"$(date) hello\" && echo $msg && echo $msg >> /mnt/nfsvol/test.log; sleep 10;done"]    
      ports:
        - name: web
          containerPort: 80
      volumeMounts:
        - name: nfsvol 
          mountPath: /mnt/nfsvol
  volumes:
    - name: nfsvol
      persistentVolumeClaim:
        claimName: nfs-pvc