- hosts: all
  become: yes
  become_user: root
  vars:
    users_group: users
    sudoers:
      - user_test

  tasks:
    - name: Make sure we have a '{{ users_group }}' group
      group:
        name: "{{ users_group }}"
        state: present

    - name: Allow '{{ users_group }}' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%{{ users_group }}'
        line: '%{{ users_group }} ALL=(ALL) NOPASSWD: ALL'
        validate: visudo -cf %s

    - name: Add sudoers users to {{ users_group }} group
      user:
        name: "{{ item }}"
        groups: "{{ users_group }}"
        append: yes
      with_items: "{{ sudoers }}"