version: '3'
services:
  dask-jupyterlab:
    image: dask-single-custom:local
    build: ./dask-single-custom
    volumes: 
      - './datasets/dask-jupyterlab:/opt/app/notebooks/dask-tutorial/data'
  minio:
    image: minio/minio:RELEASE.2019-04-18T01-15-57Z
    command: server /data
    #entrypoint: /bin/sh -c 'sleep 300'
    environment:
      - "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE"
      - "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
    ports:
     - "9000:9000"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 256M
