---
- hosts:
  - all
  become: yes
  become_user: deploy
  
  tasks:

  - name: Create folders
    file: path="{{ item }}" state=directory owner=deploy group=deploy
    with_items:
    - /opt/applications
    - /opt/applications/bash-hello-world
    - /opt/applications/bash-hello-world/logs

  - name: Copy executable
    copy:
      src: bash-hello-world.sh
      dest: /opt/applications/bash-hello-world/bash-hello-world.sh
      owner: deploy
      group: deploy
      mode: 0744

  - name: Copy service script
    copy:
      src: service.sh
      dest: /opt/applications/bash-hello-world/service.sh
      owner: deploy
      group: deploy
      mode: 0744 # -> "u=rwx,g=r,o=r"


  - name: Copy service config
    copy:
      src: bash-hello-world.service
      dest: /etc/systemd/system/bash-hello-world.service
      owner: root
      group: root
      mode: 0644 # -> "u=rw,g=r,o=r"

  - name: Restart service
    command: "sudo systemctl restart bash-hello-world"

