---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pod-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "100Mi"
  storageClassName: rook-ceph-block
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-test
  labels:
    app: pod-test
spec:
  terminationGracePeriodSeconds: 0
  nodeSelector:
    role: storage-node
  containers:
    - name: pod-test
      image: "centos:7"
      #image: "centos/python-36-centos7:latest"
      #args: ["/bin/sh", "-c", "'whoami; while true; do MSG=\"$( date ) - $HOSTNAME - hello world\"; echo \"$MSG\"; echo \"$MSG\" >> /mnt/ceph-pod-test/log.txt;  sleep 10; done'"]
      #command: ["/bin/sh"]
      #args: ["-c", "echo 'hello world' > hello-world.txt && python -m http.server  8000 "] 
      args: ["/bin/bash", "-c", "tail -f /var/log/lastlog"]
      volumeMounts:
      - name: cephvol
        mountPath: "/opt/ceph-pod-test"
  volumes:
    - name: cephvol
      persistentVolumeClaim:
        claimName: pod-test

# 